### ISSUE TITLE
Cmd X did not work on the Mac

### ISSUE THREAD

**Issue by ashishbhateja** [jiangnanandi/Obsidian-highlighter#14] opened 2022-07-25 05:37 UTC
I installed the extension but Cmd X does not seem to be working for the highlights. Is there a way to troubleshoot this? Apologies but I tried translating the Readme but could not get a fix.

**Comment by david-crafts** [comment] 2022-07-25 05:44
Is it possible that you have another plugin that is conflicting, try turning off or disabling all plugins and just keeping obsidian-highlighter.
Another possibility, did you start the plugin, press ALT+X or click on the icon to start it.


![CleanShot-2022-07-25134301@2x](https://user-images.githubusercontent.com/7147277/180706368-28254592-50d8-4e47-b345-e522d519113e.png)

**Comment by ashishbhateja** [comment] 2022-07-25 05:48
Thank you. Yes, I did start using Alt X and I am able to see the window.
I think there may be a conflict as it was working perfectly earlier. I will try and check more.

**Comment by david-crafts** [comment] 2022-07-25 06:24
I'm not sure from your description that the problem is in the ability, so if you solve the problem, post it here if it's convenient and let me know why.

Thanks。

**Comment by ashishbhateja** [comment] 2022-07-25 07:47
It seems to be triggering the edit->cut command in Safari
I am not sure how to turn it off in Safari

**Comment by david-crafts** [comment] 2022-07-25 11:00
If it's the edit->cut command, then you're probably on a page that is "editable", so the page edit state in Safari has higher priority.
Try a different page that can only be viewed but not edited

**Comment by ashishbhateja** [comment] 2022-07-25 11:05
It's a regular html page and edit command is grayed out. But the shortcut keeps looking for it. I hear a click sound. This is certainly not usual.
Yesterday, I had issues with Safari on my machine. So I downloaded the latest developer Safari beta and installed it. Could that be the cause?

**Comment by david-crafts** [comment] 2022-07-26 02:45
> 

Most likely because you have a preview version of Safari installed, if it is convenient for you, you can try to uninstall and install the official version of Safari

**Comment by david-crafts** [comment] 2023-07-14 11:55
@ashishbhateja I will close the issues first, if you still have problems, you can open this issues again

**Closed as completed** 2023-07-14 11:55 UTC
